### ISSUE TITLE
Left becomes Bottom Left on Localizable

### ISSUE THREAD

**Issue by illavoluntas** [ejbills/DockDoor#133]
After #128 string "Left" has become "Bottom left" in English, why? As the comment states "Window title alignment option", it seems strange to have text suddenly at the bottom.
Same for "Right".
String "Window Title Alignment" was adapted in "Window Titles Appear in" in English, which is inconsistent.

![Capture d’écran 2024-07-10 à 15 20 10](https://github.com/ejbills/DockDoor/assets/174935274/3899461e-e7fc-4369-9a9a-035ef72bf2eb)

**Comment by illavoluntas** [comment]
String "Window Title Alignment" was adapted in "Window Titles Appear in" in English, which is inconsistent.

**Comment by chrisharper22** [comment]
I changed this verbiage in #128 for a couple reasons. "Window Title Alignment in [Bottom Left/Bottom Right]" is the _window's_ current name, adapted from the currently opened document, tap, etc. In DockDoor, this shows up at the bottom of the preview tiles, which is why "Left" and "Right" became "Bottom Left" and "Bottom Right," respectively. This is different from the _application_ name. This is why I specified windows vs. application windows in the appearance settings.

I changed "Window Title Alignment" to "Window Titles Appear in" in the English locale, because various macOS settings use verbiage that continues the phrase within actual settings options. See below for examples within System Settings. This can be revisited if it is deemed necessary.

* Appearance:
  * Click the scroll bar to [Jump to the next page/Jump to the spot that's clicked]
* Desktop & Dock:
  * Minimize windows using [Genie Effect/Scale Effect]
  * Double-click a window's title bar to [Fill/Zoom/Minimize/Do Nothing]

**Comment by chrisharper22** [comment]
Seems that most of these changes underwent regression in #143.

**Comment by ejbills** [comment]
I see some french got removed, will get this fixed.

**Comment by ShlomoCode** [comment]
@chrisharper22 As for the English changes, I canceled them because the English version is currently the version that is hardcoded into the code. Therefore, if you think that the wording in the English version should be changed, please fix it in the code itself.

@ejbills This is indeed another reason to switch to permanent keys.. maybe there is no choice :|

**Comment by ShlomoCode** [comment]
@chrisharper22 Top Right position option added at https://github.com/ejbills/DockDoor/pull/150. I believe that now the wording "Position" makes sense 😀
![CleanShot 2024-07-11 at 06 48 18@2x](https://github.com/ejbills/DockDoor/assets/78599753/7a98c369-72c0-43bd-a6b4-348e5692ab4d)

**Comment by chrisharper22** [comment]
@ShlomoCode, good suggestion for adding more position options.

Additionally, I strongly suggest standard localization keys. I refrained from updating the hardcoded keys to prevent from breaking existing translations for the other locales. Otherwise, I would have.

When the strings undergo refactoring, I also suggest we come up with standard feature names and items. I believe "Hover Window" is too vague in use cases for the window switcher vs dock previews. I implicitly started using Dock Tiles for this, but a consensus would be nice. Also, Window vs Application titles should be described somewhere in the UI, probably as a subtitle for the main options regarding those to clear up confusion.

**Comment by ShlomoCode** [comment]
Maybe it's not so bad that the translation resets when the source string is changed, because it usually means that the meaning has changed, and I think Crowdin knows how to fetch the deleted version as a "dictionary"

**Comment by illavoluntas** [comment]
Thank you for the explanation @chrisharper22!

**Comment by ShlomoCode** [comment]
@ejbills I think it can be closed
