### ISSUE TITLE
Why Windows Switcher?

### ISSUE THREAD

**Issue by ShlomoCode** [ejbills/DockDoor#226]
I don't understand at all why DockDoor has to offer window switcher.
Why not focus on one thing ("Dock Door") and do it well?
What do we have to offer that will surpass the mature alt-tab project?
Isn't it a shame for the development efforts for the windows switcher feature, when there is already an FOSS and customizable option?

**Comment by hasansultan92** [comment]
Couple of reasons come to mind for this.

1. I like to not have to install and run several applications in my background outside the OS to do the same thing or similar stuff. For example if my OS can give me a window manager, I would rather use that than additionally install 2 other applications to make it better.

2. We are not a fork of Alt-Tab. While Alt-Tab gives me several customizations, do I really need them? I would much rather prefer a lighter weight application on my resources so I can use my resources somewhere else.

4. This application is providing Alt-Tab functionality and more, I see no reason to have 2 similar applications, linking it back to point 1. I am in favor of keeping the window switcher

6. There seems to be an active set of issues based on the window switcher so it seems like there might be more reasons people are preferring this over another existing application.

**Comment by ShlomoCode** [comment]
A window switcher is a window manager. This requires listening for window state changes in the background so that it is possible to quickly preview many windows on demand without waiting

Dock Peek is a Dock functionality, it requires tracking the mouse position, and previewing a bit, which can be done on demand quickly

You don't save any resources by reinventing the wheel and sticking the two applications into one app. You're just making yourself tons of work for something that's already been done amazingly well by others, and the end result in terms of resources, even if we manage to get to the technical level of alt-tab, will simply be the same as running DockDoor and alt-tab at the same time. The computer's resources (CPU, GPU, etc.) don't matter much whether it's 2 running applications or one. What burdens the computer are resource-intensive things, such as mouse tracking, system events, etc., which there is no way to avoid. I didn't understand what it has to do with the comparison to a built-in windows manager.

And the main point - window management is simply not related to Dock functionality. Why would they be together? Maybe we'll also add window snapping and menu bar management?

**Comment by hasansultan92** [comment]
Addressing these one by one, this is my opinion, I am sure other users will have other opinions.

Dock Peek still requires the concept of presenting windows, the same windows we are presenting in the window switcher. 

We are not reinventing the wheel, I never mentioned that. We are also not a fork of Alt-Tab meaning we have a different logical way of doing what that application has been doing. You can have two computers from different brands, they both can do the same calculations, and provide the same interfaces and features. There will still be people that like either brands because of their preferences that the other brand is not able to provide. Alt-Tab does not provide Dock peeking functionality so I see no reason to have two applications open on my computer doing the same thing. One is doing more than the other. Having two applications that do the same thing not running/active on my computer still means they are consuming resources - think disk usage that could be otherwise used by others/myself/OS.

We can look into adding the other feature set you mentioned, though with the upcoming public release of Mac OS in the fall, this is going to be native to the OS. I've mentioned above, if the OS can do it natively, I would rather use that functionality than use a 3rd party application, unless the 3rd party application provides something useful to me that the OS is not able to by default.

Perhaps the question you are asking is: how does the DockDoor name relate to the application itself? or How does the name of this application relate to the two main feature sets this application provides?

**Comment by ejbills** [comment]
On top of the dock peeking logic, it really isn't that much overhead to maintain. There is always room for alternatives, in my opinion - it will stay.
