### ISSUE TITLE
[BUG] no preview when minimizing windows via cmd+w

### ISSUE THREAD

**Issue by dannymaybach** [ejbills/DockDoor#237]
The preview of hidden/minimized windows doesn't show when minimizing a window via the cmd+w shortcut.
To reproduce this, you could open e.g. Spotify and minimize via cmd+w.

**Comment by zehDonut** [comment]
cmd+w closes the current window, so there wouldn't be a window to show?
minimize is cmd+m

**Comment by dannymaybach** [comment]
for some applications (for example Spotify) closing the window via cmd+w doesn't close the application. So it basically does the same as hiding the window.

**Comment by zehDonut** [comment]
I know, but it's not the same as minimizing the window at all.
When you press cmd+w, the window is gone. Clicking on the app will open a new window.

Some apps like spotify simply remember what you had selected before and open the same content in the new window, which is why it appears like the window was just minimized, but that isn't what's actually happening.

**Comment by illavoluntas** [comment]
> for some applications (for example Spotify) closing the window via cmd+w doesn't close the application. So it basically does the same as hiding the window.

Closing the last window of an application is usually not the same as closing an application in macOS either. So @zehDonut is right, there is literally **no** window to show because it simply no longer exists; Cmd + W closes the current window in all cases but even if the application is still running, it has no window left.

**Comment by dannymaybach** [comment]
You guys are right, that was a misunderstanding on my part. So this is actually the expected behavior and the issue can be closed.
